# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(80, 60, 583, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonRescanSerials = QtWidgets.QPushButton(self.widget)
        self.pushButtonRescanSerials.setObjectName("pushButtonRescanSerials")
        self.horizontalLayout.addWidget(self.pushButtonRescanSerials)
        self.comboBoxSerial = QtWidgets.QComboBox(self.widget)
        self.comboBoxSerial.setMinimumSize(QtCore.QSize(50, 0))
        self.comboBoxSerial.setObjectName("comboBoxSerial")
        self.horizontalLayout.addWidget(self.comboBoxSerial)
        self.pushButtonConnect = QtWidgets.QPushButton(self.widget)
        self.pushButtonConnect.setObjectName("pushButtonConnect")
        self.horizontalLayout.addWidget(self.pushButtonConnect)
        self.horizontalLayout.setStretch(1, 4)
        self.horizontalLayout.setStretch(2, 1)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(110, 120, 374, 43))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.spinBoxPowerA = QtWidgets.QSpinBox(self.widget1)
        self.spinBoxPowerA.setMaximum(100)
        self.spinBoxPowerA.setObjectName("spinBoxPowerA")
        self.verticalLayout_3.addWidget(self.spinBoxPowerA)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.spinBoxPowerB = QtWidgets.QSpinBox(self.widget1)
        self.spinBoxPowerB.setMaximum(100)
        self.spinBoxPowerB.setObjectName("spinBoxPowerB")
        self.verticalLayout_2.addWidget(self.spinBoxPowerB)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.spinBoxDelay = QtWidgets.QSpinBox(self.widget1)
        self.spinBoxDelay.setObjectName("spinBoxDelay")
        self.verticalLayout.addWidget(self.spinBoxDelay)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.pushButtonSet = QtWidgets.QPushButton(self.widget1)
        self.pushButtonSet.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSet.setFont(font)
        self.pushButtonSet.setStyleSheet("background-color : Blue")
        self.pushButtonSet.setObjectName("pushButtonSet")
        self.horizontalLayout_2.addWidget(self.pushButtonSet)
        self.pushButtonArm = QtWidgets.QPushButton(self.widget1)
        self.pushButtonArm.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonArm.setFont(font)
        self.pushButtonArm.setStyleSheet("background-color : yellow")
        self.pushButtonArm.setObjectName("pushButtonArm")
        self.horizontalLayout_2.addWidget(self.pushButtonArm)
        self.pushButtonFire = QtWidgets.QPushButton(self.widget1)
        self.pushButtonFire.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonFire.setFont(font)
        self.pushButtonFire.setStyleSheet("background-color : RED")
        self.pushButtonFire.setObjectName("pushButtonFire")
        self.horizontalLayout_2.addWidget(self.pushButtonFire)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonRescanSerials.setText(_translate("MainWindow", "Rescan Serial Ports"))
        self.pushButtonConnect.setText(_translate("MainWindow", "Connect"))
        self.label.setText(_translate("MainWindow", "PowerA"))
        self.label_2.setText(_translate("MainWindow", "PowerB"))
        self.label_3.setText(_translate("MainWindow", "Delay"))
        self.pushButtonSet.setText(_translate("MainWindow", "SET"))
        self.pushButtonArm.setText(_translate("MainWindow", "ARM"))
        self.pushButtonFire.setText(_translate("MainWindow", "FIRE"))

